# Generated by Django 5.1 on 2024-10-25 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Contenidos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tablero',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Columna',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('orden', models.PositiveIntegerField()),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contenidos.estado')),
                ('tablero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columnas', to='TableroKanban.tablero')),
            ],
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('orden', models.PositiveIntegerField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('columna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarjetas', to='TableroKanban.columna')),
                ('contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contenidos.contenidos')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contenidos.estado')),
            ],
            options={
                'permissions': [('ver_propio_tablero', 'Puede ver solo su propio contenido'), ('cambiar_estado_tarjeta', 'Puede cambiar el estado de una tarjeta')],
            },
        ),
    ]
