# Generated by Django 5.1.1 on 2024-10-03 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Contenidos', '0005_rename_autorc_comentario_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tablero',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Columna',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('orden', models.PositiveIntegerField()),
                ('tablero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columnas', to='TableroKanban.tablero')),
            ],
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('orden', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('borrador', 'Borrador')], default='activo', max_length=10)),
                ('columna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarjetas', to='TableroKanban.columna')),
                ('contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contenidos.contenidos')),
            ],
        ),
        migrations.AddIndex(
            model_name='columna',
            index=models.Index(fields=['orden'], name='TableroKanb_orden_97fa3a_idx'),
        ),
        migrations.AddIndex(
            model_name='tarjeta',
            index=models.Index(fields=['orden'], name='TableroKanb_orden_846d79_idx'),
        ),
    ]
