# Generated by Django 4.2.15 on 2024-10-24 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Contenidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Columna',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('orden', models.PositiveIntegerField()),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contenidos.estado')),
            ],
        ),
        migrations.CreateModel(
            name='Tablero',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('orden', models.PositiveIntegerField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('columna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarjetas', to='TableroKanban.columna')),
                ('contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contenidos.contenidos')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contenidos.estado')),
            ],
            options={
                'permissions': [('ver_propio_tablero', 'Puede ver solo su propio contenido'), ('cambiar_estado_tarjeta', 'Puede cambiar el estado de una tarjeta')],
            },
        ),
        migrations.AddField(
            model_name='columna',
            name='tablero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columnas', to='TableroKanban.tablero'),
        ),
    ]
