# Generated by Django 4.2.15 on 2024-10-04 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TableroKanban', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='columna',
            name='TableroKanb_orden_97fa3a_idx',
        ),
        migrations.RemoveIndex(
            model_name='tarjeta',
            name='TableroKanb_orden_846d79_idx',
        ),
    ]
