# Generated by Django 5.1.1 on 2024-10-04 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TableroKanban', '0003_remove_tarjeta_estado_columna_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablero',
            name='usuario',
        ),
    ]
