# Generated by Django 5.1.1 on 2024-10-06 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TableroKanban', '0005_alter_tarjeta_options_tarjeta_autor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarjeta',
            options={'permissions': [('ver_tablero', 'Puede ver solo su propio contenido')]},
        ),
    ]
