# Generated by Django 5.1.1 on 2024-10-06 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TableroKanban', '0006_alter_tarjeta_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarjeta',
            options={'permissions': [('ver_propio_tablero', 'Puede ver solo su propio contenido')]},
        ),
    ]
