# Generated by Django 5.1.1 on 2024-10-06 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contenidos', '0008_alter_contenidos_options'),
        ('TableroKanban', '0007_alter_tarjeta_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjeta',
            name='estado',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Contenidos.estado'),
            preserve_default=False,
        ),
    ]
