# Generated by Django 5.1.1 on 2024-10-07 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TableroKanban', '0008_tarjeta_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarjeta',
            options={'permissions': [('ver_propio_tablero', 'Puede ver solo su propio contenido'), ('cambiar_estado_tarjeta', 'Puede cambiar el estado de una tarjeta')]},
        ),
    ]
