# Generated by Django 4.2.15 on 2024-09-06 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Categoria', '0002_alter_subcategoria_categoriapadre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategoria',
            name='categoriaPadre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='Categoria.categoria'),
        ),
    ]
