# Generated by Django 5.1 on 2024-10-25 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Margenes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('der', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('izq', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('arr', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('aba', models.DecimalField(decimal_places=2, max_digits=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Plantilla',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(null=True, verbose_name='Descripcion')),
                ('disposicionHorizontal', models.BooleanField()),
                ('colorFondo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Plantilla.color')),
                ('margenes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Plantilla.margenes')),
            ],
        ),
    ]
