# Generated by Django 4.2.15 on 2024-10-22 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Plantilla', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantilla',
            name='disposicionHorizontal',
        ),
    ]
