# Generated by Django 4.2.15 on 2024-09-11 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Plantilla', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Margenes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('der', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('izq', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('arr', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('aba', models.DecimalField(decimal_places=2, max_digits=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Modulos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipoMultimedia', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tipografia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estilo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Plantilla',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(null=True, verbose_name='Descripcion')),
                ('disposicion', models.BooleanField()),
                ('colorFondo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Plantilla.color')),
                ('margenes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Plantilla.margenes')),
                ('modulos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Plantilla.modulos')),
                ('tipografia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Plantilla.tipografia')),
            ],
        ),
    ]
