# Generated by Django 4.2.15 on 2024-10-24 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plantilla', '0002_remove_plantilla_disposicionhorizontal'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantilla',
            name='disposicionHorizontal',
            field=models.BooleanField(default=False),
        ),
    ]
