# Generated by Django 4.2.15 on 2024-09-11 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Plantilla', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plantilla',
            old_name='disposicion',
            new_name='disposicionHorizontal',
        ),
    ]
