# Generated by Django 4.2.15 on 2024-09-12 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Plantilla', '0003_rename_disposicion_plantilla_disposicionhorizontal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantilla',
            name='modulos',
        ),
        migrations.RemoveField(
            model_name='plantilla',
            name='tipografia',
        ),
        migrations.DeleteModel(
            name='Modulos',
        ),
        migrations.DeleteModel(
            name='Tipografia',
        ),
    ]
