# Generated by Django 5.1 on 2024-09-06 04:10

import ckeditor.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contenidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenidos',
            name='contenido',
            field=ckeditor.fields.RichTextField(default=''),
        ),
        migrations.AddField(
            model_name='contenidos',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='contenidos',
            name='tipo',
            field=models.CharField(choices=[('IMG', 'Imagen'), ('VID', 'Video'), ('TXT', 'Texto')], max_length=3),
        ),
        migrations.AlterField(
            model_name='contenidos',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
    ]
