# Generated by Django 5.1 on 2024-11-05 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contenidos', '0003_contenidos_fecha_de_rechazados_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contenidos',
            name='fecha_de_rechazados',
        ),
        migrations.RemoveField(
            model_name='contenidos',
            name='fecha_publicacion',
        ),
    ]
