# Generated by Django 5.1.1 on 2024-09-27 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contenidos', '0004_comentario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='autorc',
            new_name='usuario',
        ),
    ]
