# Generated by Django 5.1 on 2024-09-06 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contenidos', '0004_categoria_remove_contenidos_autor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contenidos',
            options={'permissions': [('can_add', 'Puede agregar contenido'), ('can_modify', 'Puede editar contenido'), ('can_delete', 'Puede eliminar contenido')]},
        ),
    ]
