# Generated by Django 5.1 on 2024-11-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contenidos', '0005_contenidos_fecha_de_rechazados_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenidos',
            name='fecha_de_rechazados',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='contenidos',
            name='fecha_publicacion',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
