# Generated by Django 5.1 on 2024-09-12 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contenidos', '0005_alter_contenidos_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contenidos',
            options={'permissions': [('can_add', 'Puede agregar contenido'), ('can_modify', 'Puede editar contenido'), ('can_delete', 'Puede eliminar contenidos')]},
        ),
    ]
