# Generated by Django 5.1.1 on 2024-10-03 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contenidos', '0005_rename_autorc_comentario_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenidos',
            name='estado',
            field=models.CharField(default='activo', max_length=10),
        ),
    ]
