# Generated by Django 5.1 on 2024-09-12 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contenidos', '0005_alter_contenidos_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contenidos',
            name='tipo',
        ),
    ]
