# Generated by Django 5.1 on 2024-09-12 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contenidos', '0006_remove_contenidos_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('Margenes', models.CharField(max_length=50)),
                ('Color', models.CharField(max_length=7)),
            ],
        ),
        migrations.AddField(
            model_name='contenidos',
            name='plantilla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Contenidos.plantilla'),
        ),
    ]
