# Generated by Django 4.2.15 on 2024-11-07 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contenidos', '0006_alter_contenidos_fecha_de_rechazados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenidos',
            name='fecha_de_inactivacion',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
