# Generated by Django 5.1 on 2024-09-13 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contenidos', '0007_plantilla_contenidos_plantilla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenidos',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contenido', to='Contenidos.categoria'),
        ),
    ]
