# Generated by Django 5.1 on 2024-11-21 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contenidos', '0007_contenidos_fecha_de_inactivacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenidos',
            name='historial',
            field=models.TextField(blank=True, default=''),
        ),
    ]
