# Generated by Django 4.2.15 on 2024-10-04 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contenidos', '0007_estado_alter_contenidos_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contenidos',
            options={'permissions': [('can_add', 'Puede agregar contenido'), ('can_modify', 'Puede editar contenido'), ('can_delete', 'Puede eliminar contenido'), ('can_viewInactive', 'Puede ver contenido inactivo')]},
        ),
    ]
