# Generated by Django 5.1.1 on 2024-11-30 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contenidos', '0008_contenidos_historial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenidos',
            name='historial',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='contenidos',
            name='numero_lecturas',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
