# Generated by Django 4.2.15 on 2024-12-06 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contenidos', '0009_alter_contenidos_historial_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contenidos',
            options={'permissions': [('can_add', 'Puede agregar contenido'), ('can_modify', 'Puede editar contenido'), ('can_delete', 'Puede eliminar contenido'), ('can_viewInactive', 'Puede ver contenido inactivo'), ('can_viewBorrador', 'Puede ver contenido en borrador'), ('can_viewRevision', 'Puede ver contenido en revisión'), ('can_viewAceptado', 'Puede ver contenido aceptado'), ('can_change_estado', 'Puede cambiar estado'), ('can_activateContenido', 'Puede activar contenido'), ('can_viewReportes', 'Puede ver los reportes')]},
        ),
    ]
