# Generated by Django 5.1 on 2024-09-13 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contenidos', '0009_categoria_descripcion_alter_categoria_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contenidos',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='contenidos',
            name='plantilla',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Plantilla',
        ),
    ]
