# Generated by Django 4.2.15 on 2024-10-07 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contenidos', '0009_alter_contenidos_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estado',
            options={'permissions': [('can_change', 'Puede cambiar estado')]},
        ),
    ]
