# Generated by Django 5.1 on 2024-09-13 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Categoria', '0002_initial'),
        ('Contenidos', '0010_remove_contenidos_categoria_and_more'),
        ('Plantilla', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenidos',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Categoria.categoria'),
        ),
        migrations.AddField(
            model_name='contenidos',
            name='plantilla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Plantilla.plantilla'),
        ),
    ]
