# Generated by Django 4.2.15 on 2024-10-07 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contenidos', '0010_alter_estado_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estado',
            options={'permissions': [('can_change_estado', 'Puede cambiar estado')]},
        ),
    ]
