# Generated by Django 5.1.1 on 2024-10-22 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contenidos', '0014_alter_contenidos_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contenidos',
            options={'permissions': [('can_add', 'Puede agregar contenido'), ('can_modify', 'Puede editar contenido'), ('can_delete', 'Puede eliminar contenido'), ('can_viewInactive', 'Puede ver contenido inactivo'), ('can_viewBorrador', 'Puede ver contenido en borrador'), ('can_viewRevision', 'Puede ver contenido en revisión'), ('can_viewAceptado', 'Puede ver contenido aceptado'), ('can_change_estado', 'Puede cambiar estado')]},
        ),
    ]
